#ifndef CONFIG_H
#define CONFIG_H

#define BLOCK_SIZE 1024
#define BLOCK_NUM 1024
#define INODE_NUM 1024
#define BLOCK_BITMAP_BLOCK 1
#define INODE_BITMAP_BLOCK 1
#define INODE_TABLE_BLOCK 88
#define DATA_BLOCK 933
#define INODE_SIZE 88
#define EMPTY 0xFFFF
#endif
